atoi_test: atoi_test.c ../memory.c ../data.c
	gcc atoi_test.c ../memory.c ../data.c -o atoi_test

mem_test: ../memory.c ../data.c mem_test.c
	gcc mem_test.c ../memory.c ../data.c -o mem_test

clean:
	rm -f *.o atoi_test mem_test

